require 'nokogiri'
require 'open-uri'
require 'colorize'
require 'trollop'
require 'ostruct'

require 'standings/cli'
require 'standings/displayer'
require 'standings/league_reference'
require 'standings/league_results'
require 'standings/table_fetcher'
