require 'nokogiri'
require 'open-uri'
require 'colorize'
require 'trollop'
require 'pry'

require_relative '../lib/league_reference.rb'
require_relative '../lib/displayer.rb'
require_relative '../lib/table_scraper.rb'
require_relative '../lib/team.rb'