require 'nokogiri'
require 'open-uri'
require 'colorize'
require 'trollop'
require 'pry'
require 'ostruct'

require_relative '../lib/cli.rb'
require_relative '../lib/displayer.rb'
require_relative '../lib/league_reference.rb'
require_relative '../lib/league_results.rb'
require_relative '../lib/table_fetcher.rb'
